### ISSUE TITLE
AirPlay disconnects between videos

### ISSUE THREAD

**Issue by Serabe** [FrontendMasters/ios-issues#25]
TL;DR When changing videos (either by tapped on a different one or because the current one is over and automatically changes), AirPlay disconnects and reconnects.

I'm using AirPlay on an Apple TV 4K.

Let's suppose I was watching Netflix and I'm in a screen for selecting an episode of a TV Show (still in Netflix). Let's say I start watching a course and send it to the Apple TV using AirPlay. Between videos, I would be seeing the Netflix screen I was in before starting the course.

**Comment by travispomeroy** [comment]
Hello,

I'm experiencing AirPlay not working on Apple 4k TV and using iPad Frontend Masters app.  I've confirmed that AirPlay is working as expected with other apps on the iPad.  I've also confirmed that AirPlay is working on Apple TV from other devices.  All software has been updated to latest releases.

**Comment by macgregor-thompson** [comment]
I can't airplay to Apple TV to work anymore. Neither from the app nor the browser. It used to work from both. I re-signed up because I enjoy watching videos at night on things on my Apple TV. Not a computer screen. But clearly since this has been a known issue for a month (judging from the previous comment above me) and no one has even responded to him, I'll just go ahead and cancel my subscription.
